import Head from "next/head";
import {
  AiFillGithub,
  AiFillLinkedin,
  AiOutlineMail,
} from "react-icons/ai";
// import { BsFillMoonStarsFill } from "react-icons/bs";

import { useState } from "react";
import logo from "../public/logo.gif";
import Image from "next/image";

import aws from "../public/technologies/aws.png";
import bootstrap from "../public/technologies/bootstrap.png";
import css from "../public/technologies/css.png";
import flask from "../public/technologies/flask.png";
import git from "../public/technologies/git.png";
import html from "../public/technologies/html.png";
import java from "../public/technologies/java.png"
import js from "../public/technologies/javascript.png"
import react from "../public/technologies/react.png"
import py from "../public/technologies/python.png"
import node from "../public/technologies/node.png"
import mongodb from "../public/technologies/mongodb.png"
import mysql from "../public/technologies/mysql.png"
import spring from "../public/technologies/spring.png"
import tailwindcss from "../public/technologies/tailwindcss.png"

import budgetbuddy from "../public/budgetbuddy.gif"

export default function Home() {

  const techIcons = [js, html, css, aws, py, java, mysql, react, flask, node, mongodb, spring, git, bootstrap, tailwindcss];

  return (
    <div>
      <Head>
        <title>Nisrine Kane Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="md:px-20 lg:px-40 bg-gray-900">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between text-white px-2">
            <div className="flex items-center">
              <Image src={logo} alt="logo" width={50} height={50} />
              <h1 className="font-burtons text-xl">nisrinekane</h1>
            </div>
            <ul className="flex items-center">
              <li>
                <a className="bg-gradient-to-r from-cyan-500 text- to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8" href="https://drive.google.com/file/d/1PqPiFZbvkqCaY-VadtUdZnpCBjnDPLgI/view?usp=sharing" target='_blank' rel='noopener noreferrer'> Resume </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10 py-10">
            <h1 className="text-2xl mb-4 text-teal-400">Hi, my name is</h1>
            <h2 className="text-5xl py-2 font-extrabold text-custom-white md:text-6xl">
              Nisrine Kane
            </h2>
            <h3 className="text-2xl py-2 font-extrabold text-custom-gray md:text-3xl">
              Software Engineer
            </h3>
            <p className="text-md text-left py-5 leading-8 text-gray-200 max-w-xl mx-auto md:text-xl">
              I am a full stack software engineer based in Los Angeles. I am passionate about writing clean code to solve complex issues. My interests include FinTech, HealthTech and smart cities. I am currently looking for a full time position.
            </p>
            <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400">
              <a href="https://www.github.com/nisrinekane"><AiFillGithub /></a>
              <a href="https://www.linkedin.com/in/nisrinekane"><AiFillLinkedin /></a>
              <a href="mailto: nisrine@nisrinekane.com"><AiOutlineMail /></a>
            </div>
            <div className="mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 relative overflow-hidden mt-20 md:h-96 md:w-96">
            </div>
          </div>
        </section>
        <section className="px-5">
          <h3 className="text-3xl py-1 text-custom-white mb-8 mt-8">Technologies</h3>
          <div className="lg:flex lg:flex-row-wrap lg:justify-between lg:gap-2">
            {/* generate tech icons */}
            {techIcons.map((techIcon, idx) => (
              <Image key={idx} className="tech-icon" src={techIcon} />
            ))}
          </div>
        </section>
        <section className="py-10 px-5">
          <div>
            <h3 className="text-3xl py-1 text-custom-white mt-8 mb-8">Portofolio</h3>
            <div class="flex flex-row  rounded overflow-hidden shadow-lg gap-10">
              {/* budget buddy */}
              <div>
                <Image src={budgetbuddy} alt="budget buddy" />
                <div class="px-6 py-4">
                  <div class="font-bold text-xl mb-2 text-teal-500 text-left">Budget Buddy</div>
                  <p class="text-custom-gray text-base text-left mb-10">
                    Budget Buddy, an app that helps you track your spending and set goals for your budget. Features include a spending tracker, a fund tracker, a spending chart and a chat application.
                    Technologies: Python, Flask, PyMySql, SocketIO, Chart.js, npm, bcrypt and Bootstrap.
                  </p>
                </div>
              </div>
              {/* budget buddy */}
              <div>
                <Image src={budgetbuddy} alt="budget buddy" />
                <div class="px-6 py-4">
                  <div class="font-bold text-xl mb-2 text-teal-500 text-left">Budget Buddy</div>
                  <p class="text-custom-gray text-base text-left mb-10">
                    Budget Buddy, an app that helps you track your spending and set goals for your budget. Features include a spending tracker, a fund tracker, a spending chart and a chat application.
                    Technologies: Python, Flask, PyMySql, SocketIO, Chart.js, npm, bcrypt and Bootstrap.
                  </p>
                </div>
              </div>
            </div>
            {/* second line */}
            <div class="flex flex-row  rounded overflow-hidden shadow-lg gap-10">
              {/* budget buddy */}
              <div>
                <Image src={budgetbuddy} alt="budget buddy" />
                <div class="px-6 py-4">
                  <div class="font-bold text-xl mb-2 text-teal-500 text-left">Budget Buddy</div>
                  <p class="text-custom-gray text-base text-left">
                    Budget Buddy, an app that helps you track your spending and set goals for your budget. Features include a spending tracker, a fund tracker, a spending chart and a chat application.
                    Technologies: Python, Flask, PyMySql, SocketIO, Chart.js, npm, bcrypt and Bootstrap.
                  </p>
                </div>
              </div>
              {/* budget buddy */}
              <div>
                <Image src={budgetbuddy} alt="budget buddy" />
                <div class="px-6 py-4">
                  <div class="font-bold text-xl mb-2 text-teal-500 text-left">Budget Buddy</div>
                  <p class="text-custom-gray text-base text-left">
                    Budget Buddy, an app that helps you track your spending and set goals for your budget. Features include a spending tracker, a fund tracker, a spending chart and a chat application.
                    Technologies: Python, Flask, PyMySql, SocketIO, Chart.js, npm, bcrypt and Bootstrap.
                  </p>
                </div>
              </div>
            </div>

          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <div className="basis-1/3 flex-1 ">
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
