import Head from "next/head";
import {
  AiFillGithub,
  AiFillLinkedin,
  AiOutlineMail,
} from "react-icons/ai";
// import { BsFillMoonStarsFill } from "react-icons/bs";

import { useState } from "react";
import logo from "../public/logo.gif";
import Image from "next/image";

import aws from "../public/technologies/aws.png";
import bootstrap from "../public/technologies/bootstrap.png";
import css from "../public/technologies/css.png";
import flask from "../public/technologies/flask.png";
import git from "../public/technologies/git.png";
import html from "../public/technologies/html.png";
import java from "../public/technologies/java.png"
import js from "../public/technologies/javascript.png"
import react from "../public/technologies/react.png"
import py from "../public/technologies/python.png"
import node from "../public/technologies/node.png"
import mongodb from "../public/technologies/mongodb.png"
import mysql from "../public/technologies/mysql.png"
import spring from "../public/technologies/spring.png"
import tailwindcss from "../public/technologies/tailwindcss.png"

import budgetbuddy from "../public/budget_buddy.gif"
import calamarigame from "../public/calamari_game.gif"
import rickandmorty from "../public/rick_morty.gif"
import ccapproval from "../public/cc_approval.gif"

// import me from "../public/pic.png"

export default function Home() {

  const techIcons = [js, html, css, aws, py, java, mysql, react, flask, node, mongodb, spring, git, bootstrap, tailwindcss];

  return (
    <div>
      <Head>
        <title>Nisrine Kane Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="md:px-20 lg:px-40 bg-custom-bg">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between text-white px-2">
            <div className="flex items-center">
              <Image src={logo} alt="logo" width={45} height={50} />
              <h1 className="font-spaceage text-xl ml-3">nisrinekane</h1>
            </div>
            <ul className="flex items-center">
              <li>
                <a className="bg-gradient-to-r from-teal-500 text- to-cyan-500 text-white px-4 py-2 border-none rounded-md ml-8" href="https://drive.google.com/file/d/1PqPiFZbvkqCaY-VadtUdZnpCBjnDPLgI/view?usp=sharing" target='_blank' rel='noopener noreferrer'> Resume </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10 py-10">
            <h1 className="text-xl mb-4 text-custom-green">Hi, my name is</h1>
            <h2 className="text-5xl py-2 font-extrabold text-custom-white md:text-6xl">
              Nisrine Kane
            </h2>
            <h3 className="text-2xl py-2 font-extrabold text-custom-gray md:text-3xl">
              Software Engineer
            </h3>
            <p className="text-md text-center py-5 leading-8 text-gray-200 max-w-xl mx-auto md:text-xl">
              I am a full stack software engineer based in Los Angeles. I am passionate about writing clean code to solve complex issues. My interests include FinTech, HealthTech and smart cities. I am currently looking for a full time position.
            </p>
            <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400">
              <a href="https://www.github.com/nisrinekane"><AiFillGithub /></a>
              <a href="https://www.linkedin.com/in/nisrinekane"><AiFillLinkedin /></a>
              <a href="mailto: nisrine@nisrinekane.com"><AiOutlineMail /></a>
            </div>
            <div className="mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 relative overflow-hidden mt-20">
              {/* <Image src={me} alt="Nisrine Kane profile photo" width={200} height={300} /> */}
            </div>
          </div>
        </section>
        <section className="px-5">
          <h3 className="text-3xl py-1 text-custom-white mt-8 mb-2 underline decoration-custom-green">Technologies</h3>
          <p className="text-custom-gray mb-8 text-lg">Some of the technologies I use:</p>
          <div className="lg:flex lg:flex-row-wrap lg:justify-between lg:gap-2">
            {/* generate tech icons */}
            {techIcons.map((techIcon, idx) => (
              <Image key={idx} className="tech-icon" src={techIcon} />
            ))}
          </div>
        </section>
        <section className="py-10 px-5">
          <div>
            <h3 className="text-3xl py-1 text-custom-white mt-8 mb-4 underline decoration-custom-green">Portofolio</h3>
            <p className="text-custom-gray mb-8 text-lg">Some of the projects I built:</p>
            <div class="flex flex-row rounded overflow-hidden shadow-lg">
              <div className="m-10 bg-custom-blue p-8">
                <Image src={budgetbuddy} alt="budget buddy" height={270} width={500} />
                <div class="px-6 py-4">
                  <div class="font-bold text-xl mb-2 text-left text-custom-green">Budget Buddy</div>
                  <p class="text-custom-gray text-base text-left mt-5">
                    Budget Buddy, an app that helps you track your spending and set goals for your budget. Features include a spending tracker, a savings tracker,a fund tracker, a spending visualization chart and a chat application.
                  </p>
                  <p className="text-slate-500 mt-8">Technologies: Python, Flask, PyMySql, SocketIO, Chart.js, npm, bcrypt and Bootstrap.</p>
                </div>
              </div>
              {/* budget buddy */}
              <div className="m-10 bg-custom-blue p-8">
                <Image src={calamarigame} alt="calamari game" height={270} width={500} />
                <div class="px-6 py-4">
                  <div class="font-bold text-xl mb-2 text-left text-custom-green">Calamari Game</div>
                  <p class="text-custom-gray text-base text-left mb-10 mt-5">
                    Calamari Game, a multiplayer elimination game based off Squid Game and featuring 6 different games inspired by the games in the show. Features include a leaderboard, a game lobby and a game room.
                  </p>
                  <p className="text-slate-500 mt-10">Technologies: React, Node.js, SocketIO, Bootstrap.</p>
                </div>
              </div>
            </div>
            {/* second line */}
            <div class="flex flex-row rounded overflow-hidden shadow-lg">
              <div className="m-10 bg-custom-blue p-8">
                <Image src={ccapproval} alt="credit card prediction ml tool" height={270} width={500} />
                <div class="px-6 py-4">
                  <div class="font-bold text-xl mb-2 text-left text-custom-green">Credit Card ML Tool</div>
                  <p class="text-custom-gray text-base text-left mt-5">
                    A Machine Learning tool that predicts credit card approvals by using a logistic regression model. The model relies on 15 different features to predict whether a credit card application will be approved or not.
                  </p>
                  <p className="text-slate-500 mt-8">Technologies: React, Node.js, and Bootstrap</p>
                </div>
              </div>
              {/* budget buddy */}
              <div className="m-10 bg-custom-blue p-8">
                <Image src={rickandmorty} alt="rick and morty" height={270} width={500} />
                <div class="px-6 py-4">
                  <div class="font-bold text-xl mb-2 text-left text-custom-green">Rick and Morty</div>
                  <p class="text-custom-gray text-base text-left mb-10 mt-5">
                    Rick and Morty, a web app that allows you to search for your favorite Rick and Morty characters and view their information. Features include a search bar, a character list and a character details page.
                  </p>
                  <p className="text-slate-500 mt-10">Technologies: Python, Pandas, Numpy, Scikit-Learn.</p>
                </div>
              </div>
            </div>

          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <div className="basis-1/3 flex-1 ">
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
